[package]
name = "xcb-rs"
version = "0.1.0"
authors = ["B. Howe <37745048+byhowe@users.noreply.github.com>"]
license = "MIT"
edition = "2018"
description = "XCB Rust bindings."
readme = "README.md"

[dependencies]
libc = "0.2"
